spring.application.name=aeme_backend

#Server
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/AEME

#Keycloak Configuration
keycloak.server-url=http://localhost:8080
keycloak.realm=AEME
keycloak.client-id=aeme-client
keycloak.client-secret=8C3r9Db7FP9b16lOZmPIOLrFbUH7ozAf